
package com.dorayakisupplier.service.ws.LogRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.sql.SQLException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogServicePortType", targetNamespace = "http://www.dorayaki.com/api/LogService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.LogRequest.StatusCode
     * @throws LogFault
     */
    @WebMethod
    @WebResult(name = "statusCode", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
    public StatusCode addLog(
        @WebParam(name = "logType", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
        LogType params)
        throws LogFault, SQLException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.LogRequest.StatusCode
     * @throws LogFault
     */
    @WebMethod
    @WebResult(name = "deleteStatusCode", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
    public StatusCode deleteLog(
        @WebParam(name = "deleteID", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
        LogRequestIdAsLong params)
        throws LogFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.LogRequest.StatusCode
     * @throws LogFault
     */
    @WebMethod
    @WebResult(name = "updateStatusCode", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
    public StatusCode updateLog(
        @WebParam(name = "updateLogType", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
        LogType params)
        throws LogFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.LogRequest.LogTypes
     * @throws LogFault
     */
    @WebMethod
    @WebResult(name = "logTypes", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
    public LogTypes getLogs(
        @WebParam(name = "logID", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
        LogRequestIdAsLong params)
        throws LogFault, SQLException
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.LogRequest.LogType
     * @throws LogFault
     */
    @WebMethod
    @WebResult(name = "logType", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
    public LogType getLogById(
        @WebParam(name = "lgID", targetNamespace = "http://www.dorayaki.com/api/LogService", partName = "params")
        LogRequestIdAsLong params)
        throws LogFault
    ;

}
