
package com.dorayakisupplier.service.ws.DorayakiRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DorayakiServicePortType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DorayakiServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.StatusCode
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "statusCode", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public StatusCode addDorayaki(
        @WebParam(name = "dorayakiType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakiType params)
        throws DorayakiFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.StatusCode
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "deleteStatusCode", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public StatusCode deleteDorayaki(
        @WebParam(name = "deleteID", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakirequestIdAsLong params)
        throws DorayakiFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.StatusCode
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "updateStatusCode", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public StatusCode updateDorayaki(
        @WebParam(name = "updateDorayakiType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakiType params)
        throws DorayakiFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.DorayakiTypes
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "dorayakiTypes", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public DorayakiTypes getDorayakis(
        @WebParam(name = "dorayakiID", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakirequestIdAsLong params)
        throws DorayakiFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.DorayakiType
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "dorayakiType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public DorayakiType getDorayakiById(
        @WebParam(name = "drID", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakirequestIdAsLong params)
        throws DorayakiFault
    ;

}
