
package com.dorayakisupplier.service.ws.DorayakiRequest;

import com.dorayakisupplier.service.ws.LogRequest.LogFault;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.sql.SQLException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DorayakiServicePortType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DorayakiServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.StatusCode
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "updateStatusCode", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public StatusCode updateDorayaki(
        @WebParam(name = "updateDorayakiType", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakiReqType params)
            throws DorayakiFault, SQLException, LogFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.DorayakiTypes
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "dorayakiTypes", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public DorayakiTypes getDorayakiRequests(
        @WebParam(name = "dorayakiID", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        DorayakirequestIdAsLong params)
            throws DorayakiFault, SQLException, LogFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.ws.DorayakiRequest.RecipeTypes
     * @throws DorayakiFault
     */
    @WebMethod
    @WebResult(name = "recipeTypes", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
    public RecipeTypes getDorayakiRecipes(
        @WebParam(name = "recipeID", targetNamespace = "http://www.dorayaki.com/api/DorayakiService", partName = "params")
        RecipeIdAsLong params)
            throws DorayakiFault, SQLException, LogFault
    ;

}
