
package com.dorayakisupplier.service.ws.DorayakiRequest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogService", targetNamespace = "http://www.dorayaki.com/api/LogService", wsdlLocation = "file:/home/integeroverflow/Semester5/WBD/tugas-besar-2/DorayakiSupplier/src/main/java/com/dorayakisupplier/wsdl/LogRequest/LogRequestService.wsdl")
public class LogService
    extends Service
{

    private final static URL LOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSERVICE_EXCEPTION;
    private final static QName LOGSERVICE_QNAME = new QName("http://www.dorayaki.com/api/LogService", "LogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/integeroverflow/Semester5/WBD/tugas-besar-2/DorayakiSupplier/src/main/java/com/dorayakisupplier/wsdl/LogRequest/LogRequestService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSERVICE_WSDL_LOCATION = url;
        LOGSERVICE_EXCEPTION = e;
    }

    public LogService() {
        super(__getWsdlLocation(), LOGSERVICE_QNAME);
    }

    public LogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSERVICE_QNAME, features);
    }

    public LogService(URL wsdlLocation) {
        super(wsdlLocation, LOGSERVICE_QNAME);
    }

    public LogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSERVICE_QNAME, features);
    }

    public LogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogServicePortType
     */
    @WebEndpoint(name = "LogServicePort")
    public LogServicePortType getLogServicePort() {
        return super.getPort(new QName("http://www.dorayaki.com/api/LogService", "LogServicePort"), LogServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogServicePortType
     */
    @WebEndpoint(name = "LogServicePort")
    public LogServicePortType getLogServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dorayaki.com/api/LogService", "LogServicePort"), LogServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSERVICE_EXCEPTION!= null) {
            throw LOGSERVICE_EXCEPTION;
        }
        return LOGSERVICE_WSDL_LOCATION;
    }

}
