
package com.dorayakisupplier.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TutorialService", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", wsdlLocation = "file:/home/integeroverflow/Semester5/WBD/tugas-besar-2/DorayakiSupplier/src/main/java/com/dorayakisupplier/wsdl/TutorialService.wsdl")
public class TutorialService
    extends Service
{

    private final static URL TUTORIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException TUTORIALSERVICE_EXCEPTION;
    private final static QName TUTORIALSERVICE_QNAME = new QName("http://www.wstutorial.com/ws/TutorialService", "TutorialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/integeroverflow/Semester5/WBD/tugas-besar-2/DorayakiSupplier/src/main/java/com/dorayakisupplier/wsdl/TutorialService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TUTORIALSERVICE_WSDL_LOCATION = url;
        TUTORIALSERVICE_EXCEPTION = e;
    }

    public TutorialService() {
        super(__getWsdlLocation(), TUTORIALSERVICE_QNAME);
    }

    public TutorialService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TUTORIALSERVICE_QNAME, features);
    }

    public TutorialService(URL wsdlLocation) {
        super(wsdlLocation, TUTORIALSERVICE_QNAME);
    }

    public TutorialService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TUTORIALSERVICE_QNAME, features);
    }

    public TutorialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TutorialService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TutorialServicePortType
     */
    @WebEndpoint(name = "TutorialServicePort")
    public TutorialServicePortType getTutorialServicePort() {
        return super.getPort(new QName("http://www.wstutorial.com/ws/TutorialService", "TutorialServicePort"), TutorialServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TutorialServicePortType
     */
    @WebEndpoint(name = "TutorialServicePort")
    public TutorialServicePortType getTutorialServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.wstutorial.com/ws/TutorialService", "TutorialServicePort"), TutorialServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TUTORIALSERVICE_EXCEPTION!= null) {
            throw TUTORIALSERVICE_EXCEPTION;
        }
        return TUTORIALSERVICE_WSDL_LOCATION;
    }

}
