
package com.dorayakisupplier.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TutorialServicePortType", targetNamespace = "http://www.wstutorial.com/ws/TutorialService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TutorialServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.StatusCode
     * @throws TutorialFault
     */
    @WebMethod
    @WebResult(name = "statusCode", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
    public StatusCode addTutorial(
        @WebParam(name = "tutorialType", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
        TutorialType params)
        throws TutorialFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.StatusCode
     * @throws TutorialFault
     */
    @WebMethod
    @WebResult(name = "deleteStatusCode", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
    public StatusCode deleteTutorial(
        @WebParam(name = "deleteID", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
        IdAsLong params)
        throws TutorialFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.StatusCode
     * @throws TutorialFault
     */
    @WebMethod
    @WebResult(name = "updateStatusCode", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
    public StatusCode updateTutorial(
        @WebParam(name = "updateTutorialType", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
        TutorialType params)
        throws TutorialFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.TutorialTypes
     * @throws TutorialFault
     */
    @WebMethod
    @WebResult(name = "tutorialTypes", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
    public TutorialTypes getTutorials(
        @WebParam(name = "tutorialID", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
        IdAsLong params)
        throws TutorialFault
    ;

    /**
     * 
     * @param params
     * @return
     *     returns com.dorayakisupplier.service.TutorialType
     * @throws TutorialFault
     */
    @WebMethod
    @WebResult(name = "tutorialType", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
    public TutorialType getTutorialById(
        @WebParam(name = "tutID", targetNamespace = "http://www.wstutorial.com/ws/TutorialService", partName = "params")
        IdAsLong params)
        throws TutorialFault
    ;

}
