<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.dorayaki.com/api/LogService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.dorayaki.com/api/LogService">

    <wsdl:import namespace="http://www.dorayaki.com/api/LogService" location="LogRequestAbstract.wsdl" />

    <binding name="logServiceSOAPBinding" type="tns:LogServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="addLog">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="deleteLog">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="updateLog">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getLogs">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getLogById">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
    </binding>
    <service name="LogService">
        <port name="LogServicePort" binding="tns:logServiceSOAPBinding">
            <soap:address location="http://localhost:8085/api/logService" />
        </port>
    </service>
</definitions>