<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.wstutorial.com/ws/TutorialService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.wstutorial.com/ws/TutorialService">

    <wsdl:import namespace="http://www.wstutorial.com/ws/TutorialService" location="TutorialServiceAbstract.wsdl" />

    <binding name="tutorialServiceSOAPBinding" type="tns:TutorialServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="addTutorial">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="deleteTutorial">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="updateTutorial">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getTutorials">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getTutorialById">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
    </binding>
    <service name="TutorialService">
        <port name="TutorialServicePort" binding="tns:tutorialServiceSOAPBinding">
            <soap:address location="http://localhost:8090/ws/tutorialService" />
        </port>
    </service>
</definitions>