<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.dorayaki.com/api/DorayakiService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.dorayaki.com/api/DorayakiService">

    <wsdl:import namespace="http://www.wstutorial.com/api/DorayakiService" location="DorayakiRequestServiceAbstract.wsdl" />

    <binding name="dorayakiServiceSOAPBinding" type="tns:DorayakiServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="updateDorayaki">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getDorayakiRequests">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
        <operation name="getDorayakiRecipes">
            <soap:operation />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="fault">
                <soap:fault name="fault" use="literal" />
            </fault>
        </operation>
    </binding>
    <service name="DorayakiService">
        <port name="DorayakiServicePort" binding="tns:dorayakiServiceSOAPBinding">
            <soap:address location="http://localhost:8085/ws/dorayakiService" />
        </port>
    </service>
</definitions>